"""Database layer for Cortex backend."""

from src.db.database import (
    EMBEDDING_DIMENSION,
    db_connection,
    init_database,
    verify_database,
)
from src.db.models import (
    Chunk,
    ChunkCreate,
    ChunkResult,
    ComponentCheck,
    ContentType,
    ExtractedMetadata,
    HealthResponse,
    Item,
    ItemCreate,
    ItemListResponse,
    ItemMetadata,
    ItemUpdate,
    ParsedContent,
    ProcessingStatus,
    ProcessingStep,
    ProcessingUpdate,
    QueueStatus,
    RetryFailedResult,
    RetryRequest,
    RetryResponse,
    normalize_item_metadata,
)

__all__ = [
    "EMBEDDING_DIMENSION",
    "Chunk",
    "ChunkCreate",
    "ChunkResult",
    "ComponentCheck",
    "ContentType",
    "ExtractedMetadata",
    "HealthResponse",
    "Item",
    "ItemCreate",
    "ItemListResponse",
    "ItemMetadata",
    "ItemRepository",
    "ItemUpdate",
    "ParsedContent",
    "ProcessingStatus",
    "ProcessingStep",
    "ProcessingUpdate",
    "QueueStatus",
    "RetryFailedResult",
    "RetryRequest",
    "RetryResponse",
    "db_connection",
    "init_database",
    "normalize_item_metadata",
    "verify_database",
]
